# snap/snapcraft.yaml
# Copyright (C) 2020 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
name: prcs-vx68k
title: PRCS by VX68k.org
base: core18
version: "1.3.4.k2.2"
summary: PRCS unofficially updated for recent Linux-based systems
description: |
  PRCS is a legacy version control program.
  This package provides a `prcs` command updated for recent Linux-based systems.
license: GPL-2.0
confinement: strict
grade: devel
apps:
  prcs:
    command: prcs
    environment:
      RCS_PATH: ${SNAP}/usr/bin
    plugs:
      - home
parts:
  prcs:
    plugin: autotools
    source: https://bitbucket.org/kazssym/prcs/downloads/prcs-1.3.4.k2.tar.gz
    source-checksum: sha256/37b534168c0ba0f389b398566cda85bf6653be215c86c1bcbe35142c9e3bf3e9
    build-packages:
      - g++
      - rcs
    stage-packages:
      - rcs
    configflags:
      - SYS_RCS_COMMAND_PATH=/usr/bin/rcs
      - SYS_CI_COMMAND_PATH=/usr/bin/ci
      - SYS_CO_COMMAND_PATH=/usr/bin/co
      - SYS_RLOG_COMMAND_PATH=/usr/bin/rlog
